### ISSUE TITLE
Improve UX

### ISSUE THREAD

**Issue by denys-potapov** [glagoly/glagoly#4]
- [ ] Scroll issue on mobile (steps to reproduce)
- [ ] Slider below the alternative
- [ ] No need to show author of alternative (?)

**Comment by Sultanidze** [comment]
My concerns are the next:
1. when I am sliding poll page up or down, I change my selection if touch occurs on range input, it makes me mad. I propose to change this default slider behavior (by some js), or make value alterable only by moving slider thumb (by css).
2. on mobile devices in the middle of polling page it isn`t clear slider accords to question above or below, at least one time I make wrong polling, because i thought that textarea in bottom of the page only for votin comment. Therefore possibly I make wrong voting for some questions each time I return to edit my vote.

**Comment by Sultanidze** [comment]
As for me it would be better if vote scores was only positive and formed Fibonacci sequence

**Comment by denys-potapov** [comment]
@Sultanidze should be fixed now:
1) Slider doesn't responds to clicks on touch devices
2) Grouped the slider with text together. It should be more clearer on what you vote.

Note on 3) " vote scores was only positive and formed Fibonacci sequence" - we need a dislike feature. So it's even possible now, that in final results some alternatives get -1 or similar. And that means that it's unacceptable for most of users.

**Comment by Sultanidze** [comment]
@denys-potapov checked it on **Android 10**, **Chrome 86.0.4240.110** - 1) and 2) are fixed

**Comment by denys-potapov** [comment]
Thanks!
