### ISSUE TITLE
Error on FB login

### ISSUE THREAD

**Issue by denys-potapov** [glagoly/glagoly#7]
Steps to reproduce (OS, browser)?

**Comment by Sultanidze** [comment]
**Chrome desktop/android, Firefox android**:
![chrome_6ki8gcxxm4](https://user-images.githubusercontent.com/21291739/81412529-ac26fe00-914c-11ea-9f61-77e366e7e1a0.png)

It seems to be related to Facebook app restrictions:
[https://stackoverflow.com/questions/58795188/login-failed-you-cant-use-facebook-to-log-into-this-app-or-website-because-there](url)

**Firefox desktop**:
FB login doesn`t work at all because of firefox **Facebook Container** extension, just disabled it for [glagoly.com](https://glagoly.com)

**Comment by denys-potapov** [comment]
Your Login button doesn't properly reference Facebook. To fix this issue, you should always use our official SDK for Login. For more information on Login best practices, check out the Login section of our developer documents HERE.

**Comment by Sultanidze** [comment]
@denys-potapov we can use default FB button:
[https://developers.facebook.com/docs/facebook-login/web/login-button/](url)
We wont`t brake the design)))

**Comment by denys-potapov** [comment]
@Sultanidze Should be fixed now. Can you check?

**Comment by Sultanidze** [comment]
@denys-potapov checked on **Win10 x64 Firefox 82.0.2**, **Android 10, Chrome 86.0.4240.110** - Fixed.
FB authorization works now (but didn't work 3 hours ago).

**Comment by denys-potapov** [comment]
Thank! I've recieved confirmation from FB only 2 hours ago. So everything works as expected.
